### PR TITLE
[RFC] Don't blag Medium comments

### LINKED ISSUE #143: Medium responses should not be blagged
This is kind of a medium standing issue in that medium response posts to other posts are parsed as if they were primary blog posts. This could be the intended behavior, but people often express frustration that a two sentence "blog post" with a title like "great idea thanks for the info!" will show up in zulip and the feed.

I investigated the shape of medium's generated rss feeds fully expecting a boolean `response` field or a `responding to this post` field, but found no such thing. 

Shape of an initial post looked like: 

```xml
<item>                                                                                                                                                                                   
    <title></title>                                                                                                                                                                      
    <link></link>                                                                                                                                                                        
    <guid isPermaLink="false"></guid>                                                                                                                                                    
    <category></category>                                                                                                                                          
    <category></category>                                                                                                                                                
    <category></category>                                                                                                                                            
    <category></category>                                                                                                                                         
    <dc:creator></dc:creator>                                                                                                                                                            
    <pubDate></pubDate>                                                                                                                                                                  
    <atom:updated></atom:updated>                                                                                                                                                        
    <cc:license></cc:license>                                                                                                                                                            
    <content:encoded></content:encoded>
</item>
```

and a recent comment spammy culprit looks like:

```xml
<item>                                                                                                                                                                                    
    <title></title>                                                                                                                                                                      
    <link></link>                                                                                                                                                                         
    <guid isPermaLink="false"></guid>                                                                                                                                                    
    <dc:creator></dc:creator>                                                                                                                                                            
    <pubDate></pubDate>                                                                                                                                                                  
    <atom:updated></atom:updated>                                                                                                                                                        
    <content:encoded></content:encoded>                                                                                                                                              
</item>
```

The only differences here are that the "real" blog post has a license field and category fields. I am not sure if only "primary" posts have licenses, that seems possible but unlikely although it is worth looking into (I am just comparing two posts so this is a pretty small sample size), but the `category` fields, which I assume reflect the tags on the post, seem like a good option.

The "real" solution to this would be to parse medium post entries for a "primary post" or "this is a comment" boolean, but they do not provide one. It could be required to include a "blaggregator" or "RC" or even something more generic tag in order to show up on the feed and then just filter out the rest, which puts special onus on medium users to both do this and remember to do this, and requires special treatment for medium in the source, but it would solve the problem.

What do y'all think?

### PR DESCRIPTION
**Pull request by kamalmarhubi**
DO NOT MERGE since there's nothing here.

This is an empty PR for now, because I want to get feedback on what I'm planning to do since it's a bit hackish. But I find this Medium nonsense really detracts from joy of perusing the `blogging` stream, so maybe a hack is warranted.

The main observation: Medium "comment" posts have a link back to the post that is being replied to as part of their `header`, while Medium "post" posts do not. So a comment's header looks like this:

```
header
├── div
│   └── div
│       └── div
│           └── ...
└── a
    └── div
        └── div
            └── ...
```

while an ordinary post's header looks like this:

```
header
└── div
    └── div
        └── div
            └── ...
```

My proposed solution:
- add a non-null `BooleanField` called `ignored` with default `False` to the `Post` model
- modify `crawlposts` to treat links specially:
  - fetch the link
  - parse the HTML
  - query for CSS `header > a` (direct descendent) or XPATH `//header/a` (whichever is easier given choice of HTML parsing library)
  - if there is a result, set `ignored` to `True` in the generated `Post`
  - only send to Zulip if the post is not `ignored`

fixes #143 

---
- [ ] Test
- [ ] Screenshot
- [ ] AUTHORS.md entry
- [ ] CHANGES.md entry
- [ ] Documentation

### CODE REVIEW

**Comment by punchagan** [comment]
> This is an empty PR for now, because I want to get feedback on what I'm planning to do since it's a bit hackish. But I find this Medium nonsense really detracts from joy of perusing the blogging stream, so maybe a hack is warranted.

I agree that a hack is probably warranted. User experience over beautiful code. 

@kamalmarhubi Would you have the time to implement this? Or would you like me to?

**Comment by kamalmarhubi** [comment]
I can do it or not, up to you!

**Comment by punchagan** [comment]
> I can do it or not, up to you!
@kamalmarhubi  I will definitely not be able to get to this for another couple of weeks. Would you be willing to work on this? Sorry for the super delayed response.

**Comment by punchagan** [comment]
@kamalmarhubi I started using Zulip after a long break, and found the medium comments annoying.  So, I finally got around to fixing this bug. The fix is very similar to what you suggest, but it looks at the json that the Medium pages contain, rather than the html structure.

**Comment by kamalmarhubi** [comment]
Nice!

**Pull request closed without merging**
