### PR TITLE
Spruce up some links

### PR DESCRIPTION
**Pull request by strugee**
What the title says. Skipping the issue template's checklist because this patch is completely trivial.

### CODE REVIEW

**Comment by punchagan** [comment]
Thanks for the fixes.  The `readme.html` is actually generated from the `README.md`.  Can you update the PR by running [this script](https://github.com/recursecenter/blaggregator/blob/master/scripts/readme_to_about)?

**Comment by strugee** [comment]
@punchagan done!

**Comment by punchagan** [comment]
@strugee merged, thanks!

**Comment by punchagan** [comment]
@strugee Deployed.  Thanks again!

**Comment by strugee** [comment]
Sure! Thanks for merging :)

**Pull request merged**
