### PR TITLE
Title Search 

### PR DESCRIPTION
**Pull request by stanzheng**
WIP; Addresses #104 
- [ ] Test
- [x] Screenshot
- [x] AUTHORS.md entry
- [x] CHANGES.md entry
- [x] Documentation

`URL bar = http://localhost:8000/search/?q=google` 
screen shot 2017-02-07 at 11 26 56 pm

### CODE REVIEW

**Comment by stanzheng** [comment]
hi @punchagan, had a question about testing this; 

I see there's a helper method `create_posts` available in `utils`. Should I use the helper to generate a few posts with a specific post name for the test or would you suggest a different way to add a test for this.

**Comment by stanzheng** [comment]
Update:

I wrote a small test using the method I mentioned but it looks like maybe the test runner uses SQLite3 for the runner? I'm using a `postgres` full text search so I'm getting a SQL error when I run my tests which would make sense. What would you recommend?

```
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: unrecognized token: "@"
```

**Comment by punchagan** [comment]
@stanzheng This is good work. :+1: Thank you for your time, and the PR. 

> I could see manually creating post titles and then counting the ones returned from the search as a viable test. If that's adequate I can try that.

That would be good for a start, I think. Just testing that a search results the right results, and an invalid search doesn't return results. 

> I wrote a small test using the method I mentioned but it looks like maybe the test runner uses SQLite3 for the runner? I'm using a postgres full text search so I'm getting a SQL error when I run my tests which would make sense. What would you recommend?

I think we should switch the test runner to run on postgres. I probably started using sqlite to make testing faster, because some of them can take a while.  The other option could be to use Postgres only for these tests.  I won't be able to look into this until early next week.  So, if you'd like to, explore one of the options and see how it goes?

**Comment by stanzheng** [comment]
@punchagan thank you for weighing back in; It was end of batch this week so got wrapped up in a new project and going home.

I would love your help on putting the tests and postgres config; I'm not that experienced with Django would enjoy your help with reviewing the the code and making the config changes so all the past tests don't break 😄.

**Comment by punchagan** [comment]
@stanzheng Looks like you forgot to commit `search.html` and I'm unable to test this. :smile:

**Comment by stanzheng** [comment]
Ah sorry @punchagan! i was doing some weird cherry picking because I needed https://github.com/recursecenter/blaggregator/pull/137 to actively develop on my machine. 

Let me make sure `search.html` but  if you could merge that PR if its cool too!

**Comment by stanzheng** [comment]
ended up in a bit of git-fusion with cherry-picking my dev branch that I did all the work ontop of. I ended up just pushing everything including my other branch #137

**Comment by stanzheng** [comment]
@punchagan I pushed up all of my latest; I'm unsure how the test database blog titles generate their titles to search for them. It looks like Lorem Ipsum but unsure if it's the same each time. 

> ERROR: test_crawling_posts (home.tests.test_crawlposts.CrawlPostsTestCase)
> FAIL: test_should_not_edit_blog_not_logged_in (home.tests.test_views.EditBlogViewTestCase)

**Comment by punchagan** [comment]
Thanks for your work on this @stanzheng!  I've merged your code in a separate PR along with a single test.  Feel free to add more tests, or work on further improvements. I would be happy to help!

**Pull request closed without merging**
